"""Scoped broker action receipts. A UI acknowledgement permits one new attempt.

No disclaimer is accepted here and no order is generated by this module.
Exits and protective orders never consume the entry retry permission.
"""
from pathlib import Path
import json
import os
import time
import uuid
from datetime import datetime, timezone

from safe_persistence import atomic_write_json
from state_lock import critical_state_lock

DETAIL = ("OKX verlangt eine Kontobestätigung (54092). Im betroffenen OKX-Konto "
          "die von OKX verlangte TradFi-/X-Perps-Erklärung in Web/App prüfen. "
          "Danach kann hier ein erneuter regulärer Kaufversuch freigegeben werden.")
_restored = set()


def path():
    return Path(os.getenv('TRADINGBOT_TEST_STATE_DIR') or Path(__file__).resolve().parent) / 'okx_account_action.json'


def scope(account, environment):
    if not account or environment not in {'DEMO', 'LIVE'}:
        raise ValueError('OKX-Kontozuordnung fehlt')
    return environment + ':' + str(account)


def _read():
    if not path().exists():
        return {}
    data = json.loads(path().read_text())
    if not isinstance(data, dict):
        raise ValueError('OKX-Kontobestätigungszustand unlesbar')
    if any(not isinstance(row, dict) or row.get('state') not in
           {'REQUIRED', 'RETRY_ALLOWED', 'RETRY_IN_PROGRESS', 'ACCEPTED'} for row in data.values()):
        raise ValueError('OKX-Kontobestätigungszustand ungültig')
    return data


def restore_observed_rejection(account, environment):
    """Import an exact scoped recent failure from the pre-update local journal.

    Never replay an order. An acknowledgement in the new store wins. An older
    rejection behind a newer successful execution is not reactivated.
    """
    key = (str(path()), scope(account, environment))
    if key in _restored:
        return
    with critical_state_lock(path()):
        data = _read()
        if key[1] not in data:
            journal = path().with_name('decision_journal.jsonl')
            if journal.is_file():
                with journal.open('rb') as stream:
                    stream.seek(max(0, journal.stat().st_size - 4*1024*1024))
                    lines = stream.read().splitlines()
                for line in reversed(lines):
                    try:
                        row = json.loads(line)
                        if (row.get('broker') != 'okx' or row.get('account_fingerprint') != account
                                or row.get('broker_environment') != environment):
                            continue
                        stamp = datetime.fromisoformat(str(row.get('time')).replace('Z', '+00:00'))
                        if stamp.tzinfo is None or not 0 <= time.time()-stamp.timestamp() <= 7*86400:
                            continue
                        state = row.get('execution_status')
                        if state in {'FILLED', 'PARTIAL_FILLED'}:
                            break
                        if state == 'FEHLGESCHLAGEN' and '(54092)' in str(row.get('reason', '')):
                            data[key[1]] = {'state': 'REQUIRED', 'code': '54092',
                                'instrument': str(row.get('inst_id') or row.get('symbol') or ''),
                                'observed_at': stamp.timestamp(), 'revision': uuid.uuid4().hex,
                                'source': 'MIGRATED_SCOPED_DECISION_RECEIPT', 'decision_id': row.get('decision_id')}
                            atomic_write_json(path(), data)
                            break
                    except (ValueError, TypeError, AttributeError):
                        continue
        _restored.add(key)


def status(account, environment):
    try:
        row = _read().get(scope(account, environment), {})
        active = row.get('state') in {'REQUIRED', 'RETRY_ALLOWED', 'RETRY_IN_PROGRESS'}
        return {**row, 'blocked': active and row.get('state') != 'RETRY_ALLOWED',
                'required': active, 'detail': DETAIL if active else '',
                'account': account, 'environment': environment}
    except (OSError, ValueError, TypeError):
        return {'blocked': True, 'required': True, 'state': 'UNREADABLE',
                'detail': 'OKX-Kontobestätigungszustand nicht prüfbar; neue Käufe pausieren'}


def record(account, environment, *, instrument, code='54092'):
    if code != '54092':
        return
    with critical_state_lock(path()):
        data = _read()
        data[scope(account, environment)] = {'state': 'REQUIRED', 'code': code,
            'instrument': instrument, 'observed_at': time.time(), 'revision': uuid.uuid4().hex}
        atomic_write_json(path(), data)


def allow_retry(account, environment, *, revision, actor):
    with critical_state_lock(path()):
        data = _read()
        row = data.get(scope(account, environment), {})
        if row.get('revision') != revision or row.get('state') != 'REQUIRED':
            raise ValueError('Kontohinweis geändert oder bereits bestätigt; Seite neu laden')
        row.update(state='RETRY_ALLOWED', acknowledged_at=time.time(), actor=str(actor)[:80])
        atomic_write_json(path(), data)
    return status(account, environment)


def before_buy(account, environment):
    with critical_state_lock(path()):
        data = _read()
        row = data.get(scope(account, environment), {})
        if row.get('state') in {'REQUIRED', 'RETRY_IN_PROGRESS'}:
            raise ValueError(DETAIL)
        if row.get('state') == 'RETRY_ALLOWED':
            row.update(state='RETRY_IN_PROGRESS', attempted_at=time.time())
            atomic_write_json(path(), data)
            return row['revision']
    return None


def finish_retry(account, environment, revision, *, accepted=False):
    if not revision:
        return
    with critical_state_lock(path()):
        data = _read()
        row = data.get(scope(account, environment), {})
        if row.get('revision') != revision:
            return  # Never erase a newer broker rejection.
        row.update(state='ACCEPTED' if accepted else 'REQUIRED', checked_at=time.time())
        atomic_write_json(path(), data)
